version: '3'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./src:/host
            - ./nginx:/etc/nginx/conf.d/
            - ./log:/var/log/nginx/
    php:
        build: ./docker_images/php
        volumes:
            - ./src:/host
        environment:
            db_host: db
            db_user: iUser
            db_password: iDontWork
            db_db: emotes
            java: java
    db:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: iPassword
            MYSQL_USER: iUser
            MYSQL_PASSWORD: iDontWork
            TZ: UTC
        ports:
            - "8006:3306"
    java:
        build: ./docker_images/java
