version: '3'

services:
    web:
        image: nginx:latest
        ports:
            - "4980:80"
        volumes:
            - $PWD/src:/host
            - $PWD/nginx:/etc/nginx/conf.d/
            - $PWD/log:/var/log/nginx/
    php:
        build: ./docker_images/php
        volumes:
            - $PWD/src:/host
        environment:
            db_host: db
            db_user: iUser
            db_password: iDontWork
            db_db: basedata
    db:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: iPassword
            MYSQL_USER: iUser
            MYSQL_PASSWORD: iDontWork
            TZ: UTC
        ports:
            - 4906:3306
